[variables]
NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmd = "cd backend && npm install && npx prisma generate"

[phases.build]
cmd = "cd backend && npm run build"

[start]
cmd = "cd backend && npm start"
